block-list-secret-scan: []
branch: master
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
mask: []
secrets-history-timeout: 12h
secrets-scan-file-type: []
skip-check:
  - CKV_DOCKER_2
  - CKV2_GH_A1
summary-position: top
