---
name: "Pull Request: Validate"

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - edited
      - reopened
      - ready_for_review
      - synchronize

concurrency:
  group: ${{ github.head_ref }}-pr-validate
  cancel-in-progress: true

jobs:
  simple-checks:
    uses: ngnodehq/containers/.github/workflows/simple-checks.yaml@main

  get-changed-images:
    uses: ngnodehq/containers/.github/workflows/get-changed-images.yaml@main

  build-images:
    needs: [simple-checks, get-changed-images]
    if: ${{ needs.get-changed-images.outputs.addedOrModified == 'true' }}
    uses: ngnodehq/containers/.github/workflows/build-images.yaml@main
    secrets: inherit
    with:
      appsToBuild: "${{ needs.get-changed-images.outputs.addedOrModifiedImages }}"
      pushImages: false
      sendNotifications: false

  check:
    name: Check PR title
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"
          owner: ${{ github.repository_owner }}

      - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
