---
name: "Pull Request: Validate"

on:
  pull_request:
    branches: ["main"]
    types:
      - opened
      - edited
      - reopened
      - ready_for_review
      - synchronize

concurrency:
  group: ${{ github.head_ref }}-pr-validate
  cancel-in-progress: true

jobs:
  simple-checks:
    uses: ngnodehq/containers/.github/workflows/simple-checks.yaml@main

  get-changed-images:
    uses: ngnodehq/containers/.github/workflows/get-changed-images.yaml@main

  build-images:
    needs: ["simple-checks", "get-changed-images"]
    if: ${{ needs.get-changed-images.outputs.addedOrModified == 'true' }}
    uses: ngnodehq/containers/.github/workflows/build-images.yaml@main
    secrets: inherit
    with:
      appsToBuild: "${{ needs.get-changed-images.outputs.addedOrModifiedImages }}"
      pushImages: false
      sendNotifications: false

  check:
    name: Check PR title
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@f2acddfb5195534d487896a656232b016a682f3c # v1.9.0
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"
          owner: ${{ github.repository_owner }}

      - uses: amannn/action-semantic-pull-request@e9fabac35e210fea40ca5b14c0da95a099eff26f # v5
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
